str4 = """Here are two quotation marks: "". Simple enough."""
str5 = """Here are three quotation marks: ""\"."""
str6 = """Here are fifteen quotation marks: ""\"""\"""\"""\"""\"."""
str7 = """"This," she said, "is just a pointless statement.""""

one = """"one quote""""
two = """""two quotes"""""
one_space = """ "one quote" """
two_space = """ ""two quotes"" """

mismatch1 = """aaa'''bbb"""

# Three opening """, then one escaped ", then two "" (allowed), and then three
# closing """
escaped = """lol\""""""

five-quotes = """
Closing with five quotes
"""""
four-quotes = """
Closing with four quotes
""""
