name: Build binaries

on: workflow_dispatch

jobs:
  binaries:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-linux
          - x86_64-linux-gnu
          - x86_64-macos
          - aarch64-macos

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: nicknovitski/nix-develop@v1

      - name: Build project
        run: zig build --release=safe -Dtarget=${{ matrix.target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: possum_${{ matrix.target }}
          path: zig-out/bin/possum
