name: Build binaries for release

# Configure when to run the workflows.
on:
  release:
    types: [created]


jobs:
  binaries:
    defaults:
      run:
        working-directory: ./opossum

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - 4.14.0
        include:
          - os: ubuntu-latest
            possum_artifact: possum.exe
            possum_asset: possum-linux-amd64
          - os: macos-latest
            possum_artifact: possum.exe
            possum_asset: possum-macos-amd64

    runs-on: ${{ matrix.os }}

    env:
      # Ensure opam will not stop because it waits on some user input
      OPAMYES: "true"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Update opam repo
        run: opam update

      - name: Install deps
        run: opam install . --deps-only

      - name: Build project
        run: opam exec -- dune build --profile=release @install

      - name: Upload Possum binary to release
        uses: svenstaro/upload-release-action@v2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: _build/install/default/bin/${{ matrix.possum_artifact }}
          asset_name: ${{ matrix.possum_asset }}
          tag: ${{ github.ref }}
